apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandcastle-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandcastle-worker
  template:
    metadata:
      labels:
        app: sandcastle-worker
    spec:
      containers:
        - name: worker
          image: kube-sandcastle-worker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sandcastle-svc
spec:
  selector:
    app: sandcastle-worker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: isolate-worker
spec:
  podSelector:
    matchLabels:
      app: sandcastle-worker
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
